/* global console */
/* eslint-disable no-console */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const iconsDir = path.join(__dirname, '../src/icons');
const indexPath = path.join(__dirname, '../src/index.ts');

// Get all SVG files from src/icons
const svgFiles = fs
  .readdirSync(iconsDir)
  .filter((file) => file.endsWith('.svg'))
  .map((file) => file.replace('.svg', ''));

// Generate exports
const exports = svgFiles
  .map((icon) => {
    const componentName = icon
      .split('-')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');
    // SVGR generates files with PascalCase names
    return `export { default as ${componentName} } from '../dist/${componentName}';`;
  })
  .join('\n');

const indexContent = `// Auto-generated index file
// This file is generated by scripts/generate-index.mjs
// Do not edit manually

${exports}

// Re-export types
export type { SVGProps } from 'react';
`;

fs.writeFileSync(indexPath, indexContent, 'utf-8');
console.log(`Generated index.ts with ${svgFiles.length} icons`);
