/* TEST_DATABASE_URL must point to a disposable database named *_test. */
const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');
if(!process.env.TEST_DATABASE_URL||!new URL(process.env.TEST_DATABASE_URL).pathname.endsWith('_test'))throw new Error('Use a dedicated *_test database');
process.env.DATABASE_URL=process.env.TEST_DATABASE_URL;process.env.APP_ORIGIN='http://localhost:3010';
const {NestFactory}=require('@nestjs/core');const {AppModule}=require('../apps/api/dist/app.module');const prisma=require('@repo/prisma').default;let app;
async function main(){
 await prisma.$executeRawUnsafe('TRUNCATE "AuthSession","BranchUser","OrderItem","Order","OrderSession","Product","MenuCategory","Menu","ServicePoint","BranchSettings","Subscription","Branch","Tenant","User" CASCADE');
 app=await NestFactory.create(AppModule,{logger:false});await app.listen(0,'127.0.0.1');const base=await app.getUrl();
 async function request(path,method='GET',body,cookie,origin=process.env.APP_ORIGIN){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Origin:origin,...cookie?{Cookie:cookie}:{}},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
 async function signup(name,preset){const slug=name.toLowerCase();const r=await request('/auth/signup','POST',{name,slug,branchName:'Main',preset,email:`${slug}@example.com`,password:'StrongPassword123!'});assert.equal(r.status,201,JSON.stringify(r));return r;}
 const a=await signup('Alpha','QUICK_SERVICE'),b=await signup('Bravo','BAR_FLEXIBLE');assert.ok(a.cookie&&b.cookie);
 assert.equal((await request('/staff/orders')).status,401);assert.equal((await request('/admin/products','GET',undefined,a.cookie)).status,200);assert.equal((await request('/auth/login','POST',{email:'alpha@example.com',password:'StrongPassword123!'},undefined,'https://evil.example')).status,403);
 const cat=await request('/admin/categories','POST',{name:'Beer',sortOrder:1,active:true},a.cookie);assert.equal(cat.status,201,JSON.stringify(cat));const p=await request('/admin/products','POST',{name:'Leo',categoryId:cat.body.id,price:'80.10',active:true,available:true,sortOrder:1},a.cookie);assert.equal(p.status,201,JSON.stringify(p));const point=await request('/restaurant/service-points','POST',{name:'Counter',type:'PICKUP'},a.cookie);assert.equal(point.status,201,JSON.stringify(point));const path=`/public/q/${point.body.qrToken}/orders`;
 const body=()=>({requestKey:randomUUID(),method:'CASH',items:[{productId:p.body.id,quantity:2,expectedPrice:'80.10'}]});const orderBody=body();const twins=await Promise.all(Array.from({length:8},()=>request(path,'POST',orderBody)));assert.ok(twins.every(t=>t.status===201),JSON.stringify(twins));assert.equal(new Set(twins.map(t=>t.body.id)).size,1);const order=twins[0].body;assert.equal(order.total,'160.2');assert.equal(order.paymentStatus,'PENDING');assert.equal(order.requestHash,undefined);
 assert.equal((await request(path,'POST',{...orderBody,method:'PROMPTPAY'})).status,409);assert.equal((await request('/staff/orders','GET',undefined,b.cookie)).body.orders.length,0);assert.equal((await request(`/staff/orders/${order.id}`,'GET',undefined,b.cookie)).status,404);assert.equal((await request(`/staff/orders/${order.id}/payment`,'POST',{},b.cookie)).status,404);assert.equal((await request(`/admin/products/${p.body.id}/availability`,'PATCH',{available:false},b.cookie)).status,404);assert.equal((await request('/restaurant/service-points','GET',undefined,b.cookie)).body.length,0);
 assert.equal((await request(path,'POST',{...body(),total:1})).status,400);for(const quantity of [0,-1,1.5,31,'2'])assert.equal((await request(path,'POST',{...body(),items:[{productId:p.body.id,quantity,expectedPrice:'80.10'}]})).status,400);assert.equal((await request(path,'POST',{...body(),items:[{productId:p.body.id,quantity:1,expectedPrice:'70.00'}]})).status,409);
 await request(`/admin/products/${p.body.id}/availability`,'PATCH',{available:false},a.cookie);assert.equal((await request(path,'POST',body())).status,409);await request(`/admin/products/${p.body.id}/availability`,'PATCH',{available:true},a.cookie);await request(`/admin/products/${p.body.id}`,'PATCH',{price:'90',name:'New Leo'},a.cookie);const historical=await request(`/public/q/${point.body.qrToken}/orders/${order.id}`);assert.equal(historical.body.items[0].productNameSnapshot,'Leo');assert.equal(historical.body.items[0].unitPriceSnapshot,'80.1');assert.equal((await request(path,'POST',body())).status,409);
 const status=x=>request(`/staff/orders/${order.id}/status`,'PATCH',{status:x},a.cookie);assert.equal((await status('COMPLETED')).status,409);for(const s of ['ACCEPTED','PREPARING','READY','COMPLETED'])assert.equal((await status(s)).status,200);const paid=await request(`/staff/orders/${order.id}/payment`,'POST',{},a.cookie);assert.equal(paid.body.paymentStatus,'PAID');assert.equal((await status('CANCELLED')).status,409);
 const noQr=await request(path,'POST',{requestKey:randomUUID(),method:'PROMPTPAY',items:[{productId:p.body.id,quantity:1,expectedPrice:'90.00'}]});assert.equal(noQr.status,400);const set=await request('/restaurant/settings','PATCH',{qrMode:'PERMANENT',sessionMode:'SINGLE_ORDER',paymentMode:'PER_ORDER',fulfillmentMode:'PICKUP',promptpayId:'0812345678'},a.cookie);assert.equal(set.status,200,JSON.stringify(set));const qr=await request(path,'POST',{requestKey:randomUUID(),method:'PROMPTPAY',items:[{productId:p.body.id,quantity:1,expectedPrice:'90.00'}]});assert.equal(qr.status,201,JSON.stringify(qr));const payQr=await request(`/public/q/${point.body.qrToken}/orders/${qr.body.id}/promptpay`);assert.equal(payQr.status,200,JSON.stringify(payQr));assert.match(payQr.body.svg,/<svg/);assert.equal(qr.body.paymentStatus,'PENDING');
 const claimPath=`${path}/${qr.body.id}/payment-claim`;const claim=await request(claimPath,'POST',{reference:'CUSTOMER-123',note:'KBank 20:15'});assert.equal(claim.status,201,JSON.stringify(claim));assert.equal(claim.body.paymentClaim.status,'SUBMITTED');assert.equal((await request(`/staff/orders/${qr.body.id}/payment`,'POST',{},a.cookie)).status,400);assert.equal((await request(`/staff/orders/${qr.body.id}/payment-claim/reject`,'POST',{reason:'No matching deposit'},a.cookie)).status,201);assert.equal((await request(`${path}/${qr.body.id}`)).body.paymentClaim.status,'REJECTED');assert.equal((await request(claimPath,'POST',{reference:'CUSTOMER-456'})).body.paymentClaim.status,'SUBMITTED');assert.equal((await request(`/staff/orders/${qr.body.id}/payment`,'POST',{reference:'BANK-TXN-789',note:'Matched amount and recipient'},b.cookie)).status,404);const qrPaid=await request(`/staff/orders/${qr.body.id}/payment`,'POST',{reference:'BANK-TXN-789',note:'Matched amount and recipient'},a.cookie);assert.equal(qrPaid.status,201);assert.equal(qrPaid.body.paymentStatus,'PAID');const verified=await request(`/staff/orders/${qr.body.id}`,'GET',undefined,a.cookie);assert.equal(verified.body.paymentClaim.status,'VERIFIED');assert.equal(verified.body.paymentReference,'BANK-TXN-789');
 const refund=await request(`/staff/orders/${qr.body.id}/refunds`,'POST',{amount:'40',method:'BANK_TRANSFER',reason:'Customer requested partial refund'},a.cookie);assert.equal(refund.status,201,JSON.stringify(refund));assert.equal((await request(`/staff/orders/${qr.body.id}/refunds/${refund.body.id}/complete`,'POST',{},a.cookie)).status,400);assert.equal((await request(`/staff/orders/${qr.body.id}/refunds/${refund.body.id}/complete`,'POST',{reference:'REFUND-TXN-1'},a.cookie)).status,201);assert.equal((await request(`/staff/orders/${qr.body.id}/refunds`,'POST',{amount:'51',method:'CASH',reason:'Too much'},a.cookie)).status,409);const pendingRefund=await request(`/staff/orders/${qr.body.id}/refunds`,'POST',{amount:'50',method:'CASH',reason:'Remaining amount'},a.cookie);assert.equal(pendingRefund.status,201);assert.equal((await request(`/staff/orders/${qr.body.id}/refunds/${pendingRefund.body.id}/cancel`,'POST',{},a.cookie)).status,201);const refundDetail=await request(`/staff/orders/${qr.body.id}`,'GET',undefined,a.cookie);assert.deepEqual(refundDetail.body.refunds.map(r=>r.status).sort(),['CANCELLED','COMPLETED']);
 const catB=await request('/admin/categories','POST',{name:'Beer',sortOrder:1,active:true},b.cookie);const pb=await request('/admin/products','POST',{name:'Chang',categoryId:catB.body.id,price:'70',active:true,available:true},b.cookie);const spB=await request('/restaurant/service-points','POST',{name:'A3',type:'BAR_SEAT'},b.cookie);const sess=await request('/restaurant/sessions','POST',{servicePointId:spB.body.id,label:'A3',description:'Left bar'},b.cookie);assert.equal(sess.status,201,JSON.stringify(sess));const spath=`/public/s/${sess.body.token}/orders`;const sb=()=>({requestKey:randomUUID(),method:'CASH',items:[{productId:pb.body.id,quantity:1,expectedPrice:'70'}]});assert.equal((await request(spath,'POST',sb())).status,201);assert.equal((await request(spath,'POST',sb())).status,201);assert.equal((await request(`/restaurant/sessions/${sess.body.id}`,'PATCH',{label:'Zone C4'},b.cookie)).status,200);assert.equal((await request(`/public/s/${sess.body.token}/menu`)).body.session.label,'Zone C4');assert.equal((await request(`/restaurant/sessions/${sess.body.id}/close`,'POST',{},b.cookie)).status,201);assert.equal((await request(spath,'POST',sb())).status,409);
 const otherCat=await request('/admin/categories','POST',{name:'Other',sortOrder:1,active:true},b.cookie);assert.equal((await request(`/admin/products/${p.body.id}`,'PATCH',{categoryId:otherCat.body.id},b.cookie)).status,404);
 const summary=await request('/staff/summary','GET',undefined,a.cookie);assert.equal(summary.status,200,JSON.stringify(summary));assert.ok(Number(summary.body.total)>=160.2);
 const c=await signup('Charlie','TABLE_SERVICE');const cc=await request('/admin/categories','POST',{name:'Coffee',sortOrder:1,active:true},c.cookie);const cp=await request('/admin/products','POST',{name:'Latte',categoryId:cc.body.id,price:'65',active:true,available:true},c.cookie);const cpoint=await request('/restaurant/service-points','POST',{name:'Table 1',type:'TABLE'},c.cookie);const cpath=`/public/q/${cpoint.body.qrToken}/orders`;const cb=()=>({requestKey:randomUUID(),method:null,items:[{productId:cp.body.id,quantity:1,expectedPrice:'65'}]});assert.equal((await request(cpath,'POST',cb())).status,201);assert.equal((await request(cpath,'POST',cb())).status,201);const csessions=await request('/restaurant/sessions','GET',undefined,c.cookie);assert.equal(csessions.body.length,1);const csid=csessions.body[0].id;assert.equal((await request(`/restaurant/sessions/${csid}/close`,'POST',{method:'CASH'},c.cookie)).status,201);assert.equal((await request(`/restaurant/sessions/${csid}/payment`,'POST',{},c.cookie)).status,201);const csummary=await request('/staff/summary','GET',undefined,c.cookie);assert.equal(csummary.body.cash,'130');assert.equal((await request('/restaurant/branches','POST',{name:'Second',slug:'second',preset:'QUICK_SERVICE'},c.cookie)).status,409);
 const staff=await request('/restaurant/staff','POST',{email:'charlie-staff@example.com',password:'StrongPassword123!',role:'STAFF'},c.cookie);assert.equal(staff.status,201);const staffLogin=await request('/auth/login','POST',{email:'charlie-staff@example.com',password:'StrongPassword123!'});assert.equal((await request('/admin/categories','GET',undefined,staffLogin.cookie)).status,200);assert.equal((await request('/admin/categories','POST',{name:'Forbidden',sortOrder:2,active:true},staffLogin.cookie)).status,403);assert.equal((await request('/restaurant/staff','GET',undefined,staffLogin.cookie)).status,403);
 console.log('PASS tenant isolation, concurrent idempotency, scoped management, current prices, historical snapshots, status/payment transitions, permanent and session QR, PromptPay claims and bank references, manual refunds, reporting');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(app)await app.close();await prisma.$disconnect();});
