/* Run only against a dedicated test database: TEST_DATABASE_URL=... npm run test:integration */
const assert = require('node:assert/strict');
const {randomUUID}=require('node:crypto');
if(!process.env.TEST_DATABASE_URL || !new URL(process.env.TEST_DATABASE_URL).pathname.endsWith('_test')) throw new Error('TEST_DATABASE_URL must name a dedicated database ending in _test');
process.env.DATABASE_URL=process.env.TEST_DATABASE_URL;
process.env.APP_ORIGIN='http://localhost:3010';
process.env.PROMPTPAY_QR_URL='/payment-qr.svg';
const {NestFactory}=require('@nestjs/core');
const {AppModule}=require('../apps/api/dist/app.module');
const prisma=require('@repo/prisma').default;
const {hashPassword}=require('../apps/api/dist/security/password');
let app;
async function main(){
 await prisma.payment.deleteMany();await prisma.orderItem.deleteMany();await prisma.order.deleteMany();await prisma.menuItem.deleteMany();await prisma.menuCategory.deleteMany();await prisma.table.deleteMany();await prisma.session.deleteMany();await prisma.user.deleteMany();
 const password=randomUUID();
 await prisma.user.create({data:{email:'test-admin@example.com',passwordHash:hashPassword(password),role:'ADMIN'}});
 await prisma.user.create({data:{email:'test-staff@example.com',passwordHash:hashPassword(password),role:'STAFF'}});
 const table=await prisma.table.create({data:{name:'A7'}});
 const other=await prisma.table.create({data:{name:'B2'}});
 const category=await prisma.menuCategory.create({data:{name:'Beer'}});
 const item=await prisma.menuItem.create({data:{name:'Leo',price:'80.10',categoryId:category.id}});
 app=await NestFactory.create(AppModule,{logger:false});await app.listen(0,'127.0.0.1');const base=await app.getUrl();
 async function request(path,method='GET',body,cookie,origin=process.env.APP_ORIGIN){
  const res=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Origin:origin,...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});
  return {status:res.status,body:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};
 }
 const body=()=>({requestKey:randomUUID(),method:'CASH',items:[{menuItemId:item.id,quantity:2,expectedPrice:'80.10'}]});
 const path=`/public/tables/${table.qrToken}/orders`;
 assert.equal((await request('/staff/orders')).status,401);
 assert.equal((await request('/admin/menu')).status,401);
 assert.equal((await request('/public/tables/not-a-token/menu')).status,404);
 assert.equal((await request('/auth/login','POST',{email:'test-admin@example.com',password},undefined,'https://evil.example')).status,403);
 const admin=await request('/auth/login','POST',{email:'test-admin@example.com',password});assert.equal(admin.status,200);assert.match(admin.cookie,/ros_session=/);
 const staff=await request('/auth/login','POST',{email:'test-staff@example.com',password});assert.equal(staff.status,200);
 assert.equal((await request('/admin/menu','GET',undefined,staff.cookie)).status,403);
 console.log('PASS authentication, roles, invalid QR and request origin');
 const newBody=body();const twins=await Promise.all(Array.from({length:8},()=>request(path,'POST',newBody)));
 assert.ok(twins.every(t=>t.status===201),JSON.stringify(twins));
 assert.equal(new Set(twins.map(t=>t.body.id)).size,1);assert.equal(await prisma.order.count(),1);
 const order=twins[0].body;assert.equal(order.total,'160.2');assert.equal(order.payment.amount,'160.2');assert.equal(order.payment.status,'PENDING');assert.equal(order.status,'NEW');assert.equal(order.requestHash,undefined);
 assert.equal((await request(path,'POST',{...newBody,method:'QR'})).status,409);
 assert.equal((await request(`/public/tables/${other.qrToken}/orders`,'POST',newBody)).status,409);
 assert.equal((await request(`/public/tables/${other.qrToken}/orders/${order.id}`)).status,404);
 console.log('PASS 8 concurrent duplicate submissions create exactly one order, decimal totals and table isolation');
 for(const quantity of [0,-1,1.5,31,'2']) assert.equal((await request(path,'POST',{...body(),items:[{menuItemId:item.id,quantity,expectedPrice:'80.10'}]})).status,400);
 assert.equal((await request(path,'POST',{...body(),total:1})).status,400);
 const duplicate=body();duplicate.items.push(duplicate.items[0]);assert.equal((await request(path,'POST',duplicate)).status,400);
 assert.equal((await request(path,'POST',{...body(),items:[{menuItemId:item.id,quantity:1,expectedPrice:'79.00'}]})).status,409);
 await prisma.menuItem.update({where:{id:item.id},data:{available:false}});assert.equal((await request(path,'POST',body())).status,409);
 await prisma.menuItem.update({where:{id:item.id},data:{available:true,active:false}});assert.equal((await request(path,'POST',body())).status,409);
 await prisma.menuItem.update({where:{id:item.id},data:{active:true}});await prisma.menuCategory.update({where:{id:category.id},data:{active:false}});assert.equal((await request(path,'POST',body())).status,409);
 await prisma.menuCategory.update({where:{id:category.id},data:{active:true}});await prisma.table.update({where:{id:table.id},data:{active:false}});assert.equal((await request(path,'POST',body())).status,404);await prisma.table.update({where:{id:table.id},data:{active:true}});
 assert.equal(await prisma.order.count(),1);assert.equal(await prisma.payment.count(),1);
 console.log('PASS quantity, payload, price, availability, category and inactive table checks without partial writes');
 const next=await request(path,'POST',body());assert.notEqual(next.body.id,order.id);
 await prisma.menuItem.update({where:{id:item.id},data:{price:'90',name:'New Leo'}});
 const historical=await request(`/public/tables/${table.qrToken}/orders/${order.id}`);assert.equal(historical.body.items[0].name,'Leo');assert.equal(historical.body.total,'160.2');assert.equal(historical.body.items[0].unitPrice,'80.1');
 await prisma.menuItem.update({where:{id:item.id},data:{price:'80.10'}});
 const status=target=>request(`/staff/orders/${order.id}/status`,'PATCH',{status:target},staff.cookie);
 assert.equal((await status('SERVED')).status,409);
 for(const target of ['ACCEPTED','PREPARING','SERVED']) assert.equal((await status(target)).status,200);
 assert.ok((await request('/staff/orders','GET',undefined,staff.cookie)).body.orders.some(o=>o.id===order.id),'Unpaid served orders remain active');
 const paid=await request(`/staff/orders/${order.id}/payment`,'POST',{},staff.cookie);assert.equal(paid.body.status,'PAID');
 assert.equal((await request(`/staff/orders/${order.id}/payment`,'POST',{},staff.cookie)).body.paidAt,paid.body.paidAt);
 assert.ok(!(await request('/staff/orders','GET',undefined,staff.cookie)).body.orders.some(o=>o.id===order.id));
 console.log('PASS repeated independent ordering, historical snapshots, transitions, served/unpaid visibility, idempotent payment confirmation');
 const qr=await request(path,'POST',{...body(),method:'QR'});assert.equal(qr.body.payment.status,'PENDING');
 assert.equal((await request(`/staff/orders/${qr.body.id}/payment`,'POST',{},staff.cookie)).body.status,'PAID');
 assert.equal((await request(`/staff/orders/${qr.body.id}/status`,'PATCH',{status:'CANCELLED'},staff.cookie)).status,409);
 const cancel=await request(`/staff/orders/${next.body.id}/status`,'PATCH',{status:'CANCELLED'},staff.cookie);assert.equal(cancel.body.payment.status,'CANCELLED');
 assert.equal((await request(`/staff/orders/${next.body.id}/payment`,'POST',{},staff.cookie)).status,409);
 const race=await request(path,'POST',body());await Promise.all([request(`/staff/orders/${race.body.id}/status`,'PATCH',{status:'CANCELLED'},staff.cookie),request(`/staff/orders/${race.body.id}/payment`,'POST',{},staff.cookie)]);
 const raced=await prisma.order.findUnique({where:{id:race.body.id},include:{payment:true}});assert.ok(!(raced.status==='CANCELLED'&&raced.payment.status==='PAID'));
 console.log('PASS manual QR remains pending until staff receipt, paid cancellation protection and cancel/payment race');
 const abort=new AbortController();const stream=await fetch(base+'/staff/events',{headers:{Cookie:staff.cookie},signal:abort.signal});assert.equal(stream.status,200);assert.match(stream.headers.get('content-type'),/text\/event-stream/);
 const reader=stream.body.getReader();const initial=new TextDecoder().decode((await reader.read()).value);assert.match(initial,/connected/);
 const eventOrder=await request(path,'POST',body());let eventText='';while(!eventText.includes('"kind":"new"'))eventText+=new TextDecoder().decode((await reader.read()).value);assert.match(eventText,new RegExp(eventOrder.body.id));abort.abort();
 const qrImage=await fetch(base+`/admin/tables/${table.id}/qr`,{headers:{Cookie:admin.cookie}});assert.equal(qrImage.status,200);assert.match(await qrImage.text(),/<svg/);
 const rotated=await request(`/admin/tables/${table.id}/token`,'POST',{},admin.cookie);assert.notEqual(rotated.body.qrToken,table.qrToken);assert.equal((await request(`/public/tables/${table.qrToken}/menu`)).status,404);
 const summary=await request('/staff/summary','GET',undefined,staff.cookie);assert.equal(summary.status,200);assert.ok(Number(summary.body.total)>=320.4);
 await request('/auth/logout','POST',{},staff.cookie);assert.equal((await request('/staff/orders','GET',undefined,staff.cookie)).status,401);
 console.log('PASS SSE delivery, table QR generation/rotation, Bangkok summary and logout revocation');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(app)await app.close();await prisma.$disconnect();});
